name: Multi OS
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ${{matrix.os}}
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - run: echo "Hello from ${{matrix.TARGET}}"

